### PR TITLE
Add draft 3 or lecture 6 notes

### PR DESCRIPTION
**Pull request by standardpointer**
This is the third draft of lecture 6's notes.

Removed some odd formatting in which precluded "Distributed" to be
bold.`

### CODE REVIEW

**Comment by kevinaangstadt** [comment]
@superslalomracer could you please review this PR? Your review may need to be added as comments to this PR because of our permissions setup.

**Comment by standardpointer** [comment]
Already working on editing the commit messages, based on Kevin's advice on my other PRs @superslalomracer! Will have them updated by tonight.

**Comment by superslalomracer** [comment]
@musicalkeyboard1234 sounds great. I've looked at your file and the formatting seems to be up to date. I agree that your commits could be more descriptive as to what specific formatting you changed, but your most recent commit it great.

**Review by superslalomracer — APPROVED** [review]
These look great. File content is perfect, Commit Messages are good.

**Pull request merged**
