### PR TITLE
Add Lecture 9 Notes

### PR DESCRIPTION
**Pull request by superslalomracer**
This adds the lecture 9 notes in the form of the file Lecture_09.md. The file conforms to current naming and spacing conventions, as well as the proposed formatting template. 

Topics covered in the lecture 9 notes include quality assurance, types of software quality, and types of software testing.

### CODE REVIEW

**Comment by kevinaangstadt** [comment]
@musicalkeyboard1234 could you please review this PR?  Due to permissions, you may need to provide your review using comments.

**Review by standardpointer — CHANGES_REQUESTED** [review]
Overall, this commit is great! I like the clean format. I was just wondering if the overview portion (starting on line 5)  is necessary? Though, this has been discussed in issue #33, and I'm not sure if you're already working on this or not.

Nonetheless, everything looks fine!

**Comment by superslalomracer** [comment]
Great! The file has been updated to match the current agreed-upon format.

**Review by standardpointer — APPROVED** [review]
Nice. Everything looks fantastic. Content looks accurate, formatting is great.

**Pull request merged**
