### PR TITLE
Add Lecture 07 Notes

### PR DESCRIPTION
**Pull request by epuer18**
Add Lecture_07.md file to the repository. This file contains notes on git branching and remote repositories. There is also a section called "Git Review" that prefaces these with notes on commits and the git tree. Useful git commands for each of these sections are highlighted in their own subsections with explanations.

### CODE REVIEW

**Comment by kevinaangstadt** [comment]
@cailemieuxmack could you please review this PR?  Be sure to look at both content and the commit messages.  You may need to complete your review using the comments due to permissions.

**Review by cailemieuxmack — COMMENTED** [review]
I think what you have here is good and it mostly conforms to the style guidelines set out in the template. Your commit messages are good and follow the guidelines set in class. The only thing I would change is at the bottom where you give a lot of git commands and their uses, it looks like they are definitions at first glance. I would like you to use back ticks to make it more obvious that they are commands. Ex/ `git pull` - git fetch + git merge

**Comment by cailemieuxmack** [comment]
I didn't realize that the comments would use the markdown syntax... Here is what I meant:
Ex/ \`git pull\` - git fetch + git merge

**Comment by epuer18** [comment]
Thanks, @cailemieuxmack I agree with your feedback. I corrected that and just made a commit with the corresponding changes.

**Pull request merged**
